### ISSUE TITLE
what changes you made (does it make heroku safe?) and how to deploy on heroku as the guide URL is not available

### ISSUE THREAD

**Issue by traviss64** [professorop/247-Mirror-Bot#1]
Just the title

**Comment by professorop** [comment]
Just simple changes like, ui, user info
Deploy from action workflows
Don't know, idk why heroku banning accounts, try yourself

**Comment by professorop** [comment]
Just simple changes like, ui, user info
Deploy from action workflows
Don't know, idk why heroku banning accounts, try yourself
